# Generated by Django 4.2.6 on 2024-03-04 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0002_fin_delivery_challan_fin_delivery_challan_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_delivery_challan_items',
            name='delivery_challan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_delivery_challan'),
        ),
        migrations.AlterField(
            model_name='fin_delivery_challan_items',
            name='discount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fin_delivery_challan_items',
            name='tax_rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fin_delivery_challan_items',
            name='total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
