# Generated by Django 4.2.6 on 2024-03-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0004_alter_employee_comment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_delivery_challan',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
