# Generated by Django 4.2.6 on 2024-03-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0005_fin_delivery_challan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_delivery_challan_items',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
