# Generated by Django 4.2.6 on 2024-03-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0007_fin_debit_note_alter_employee_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fin_debit_note',
            name='bank_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fin_debit_note',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fin_debit_note',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
